### ISSUE TITLE
JSON datasource

### ISSUE THREAD

**Issue by tdyas** [grafana/simple-json-datasource#1]
How might this datasource compare with the JSON datasource I was writing? Available at https://github.com/foursquare/grafana/tree/v2_fs/public/app/plugins/datasource/json

**Comment by sbouchex** [comment]
+1, why not merging both and have a official JSON datasource ?

**Comment by tdyas** [comment]
I'm in favor of that.

Just a technical question to discuss: The generic datasource seems to support one URL per instance of the datasource (like every other datasource), while my JSON datasource supports configuring multiple URLs in a single instance of the datasource.

I think I will go with the way the generic datasource does it. The JSON datasource has the issue that the backend doesn't support proxying each URL since it only supports that for a single URL per datasource. I ended up having to make changes in the backend to try and support that proxying but never got far with it.

The approach of the generic datasource makes sense especially given the existence of the mixed datasource.

**Comment by sbouchex** [comment]
Make sense, I will go to:
- A simple url which can be configured (including username, password...)
- 2 endpoints: One to query the metric names, one to query the metric values

**Comment by tdyas** [comment]
For the JSON plugin, my goal was a more general scope than that. The goal was to allow Grafana to query endpoints where the Grafana administrators may not have control over the endpoints.

Thus the URL (and eventually body) would allow template parameters. The JSON data source defines two right now: `from` and `to` based on the panel's time range. The further work I was going to do would be to add other template parameters (along with ways of defining values for them, whether by configuration or allowing a URL to be queried).

This seems a more general version of the Generic Datasource's scope.

Thoughts?

**Comment by sbouchex** [comment]
yep, that's another approach. As long as there is a possibility to define a way to query metrics names and query metrics values. That's fine.

**Comment by tdyas** [comment]
Yeah, there would be that possibility. For each template parameter, there would be the option to define an endpoint to return the allowed values.

**Comment by bergquist** [comment]
Our initial goal for this project was to have an example implementation of a custom datasource rather then having documentation that might be lagging. 

But since we are pushing more for plugins I think it would be better to have such example within grafana core itself (then we cannot forget to upgrade it etc).

**Comment by tral** [comment]
_tdyas_ can you briefly describe what json format to use with your forsquareJSON plugin?

I use something like that:
`[{"target":"metric1","datapoints":[[2,1456851632000],[2,1456851632000]]},{"target":"metric2","datapoints":[[2,1456851632000],[2,1456851632000]]}]`

and got nothing: http://dn.imagy.me/201603/01/a467ecd28a8d7e5dda167c814fc6fdde.png

Maybe you have an example?

**Comment by bergquist** [comment]
@tdyas have you done any more work on your plugin? Anything missing from this? except the possibility to change the url.

**Comment by tdyas** [comment]
I haven't. The particular use case that motivated the plugin went away.

**Comment by bergquist** [comment]
@tdyas Ok. Then I'll close this issue.
