### ISSUE TITLE
Rename repo to grafana-simple-json-datasource

### ISSUE THREAD

**Issue by gianluca-sabena** [grafana/simple-json-datasource#10]
Since the plugin is called grafana-simple-json-datasource (from plugin.json) and the folder in ```grafana/public_gen/app/plugins/datasource/grafana-simple-json-datasource```  must be equal to plugin name  it's better to have the same name

This rename clarify repository content after a user fork it

**Comment by bergquist** [comment]
The first part of the plugin name should match the github organisation name. 
I understand this name is annoying when forking it but its very easy to name the cloned folder something else. 

This repo is linked to in a lot of places. So renaming it would require lots of validation.
