### ISSUE TITLE
/query  response not properly handled by grafana server when /search returns map?

### ISSUE THREAD

**Issue by andig** [grafana/simple-json-datasource#101]
Search API allows map response according to docs:

    [ { "text" :"upper_25", "value": 1}, { "text" :"upper_75", "value": 2} ]

When- after successful `/search` with map response- grafana issues `/query` requests it will always use `value` for the query and hence- when `value` is returned as `target` In the `/query` response, update the panel's legend with `value` instead of `text` as expected.

Imho grafana should continue to use `text` aven when the query returns `value`. 

What is the proper way to return `target` for such `/query` requests- use `text` instead of `value`?

**Comment by andig** [comment]
ping @daniellee last response to issues or prs is more than a month old- any chance to get updates?

**Comment by daniellee** [comment]
Most of the team has been on vacation (heatwave here in Europe) but now we are mostly back.

I don't understand the issue exactly. 

> When- after successful /search with map response- grafana issues /query requests it will always use value for the query and hence- when value is returned as target In the /query response, update the panel's legend with value instead of text as expected.

You can have any value you want in the query response. You decide what the legend value is. The fake simple json datasource reuses the target values because that is easiest but you can map them back to text values.

So if I understand correctly this is something you can fix in your own backend and does not need any changes in Grafana.

**Comment by andig** [comment]
hi @daniellee thanks for the reply. The downtime wasn't transparent ;)

My question is really this:

  - search response allows text/value for targets
  - query request always sends value (not text!) for target

Now, when query response replies with value this will override the metric title. Imho:

  - query request/response should *always* use value (NOT text)
  - the value->text mapping for query response should happen on grafana side, not in the plugin

Does this make sense?

**Comment by andig** [comment]
**Resolution**: this plugin exposes the internal API. That API expect `query` response in the order of the requested targets. The backend does not perform any sort of mapping. The `search` text/value support is only used for metric selection.

**Comment by mrvic** [comment]
![image](https://user-images.githubusercontent.com/6241361/55472862-6c1e4f00-560d-11e9-86d0-96bb99902116.png)
