### ISSUE TITLE
fields not updating in the editor

### ISSUE THREAD

**Issue by sresam89** [grafana/simple-json-datasource#105]
I am trying to add another field to the UI code to fetch the tags. If i hardcode a tag value in the panel JSON, it loads it the first time, but when i Click on it and change it the value goes to "undefined"

Initial page load
![image](https://user-images.githubusercontent.com/21145490/43052512-fbe15d2a-8deb-11e8-8c10-1d2a346be159.png)

My Option getting populated
![image](https://user-images.githubusercontent.com/21145490/43052407-3f902ce6-8deb-11e8-99eb-b73b7000cd72.png)

After I click on any option
![image](https://user-images.githubusercontent.com/21145490/43052524-17643b94-8dec-11e8-87ce-eff5956398f4.png)

query editor.html

` 
<query-editor-row query-ctrl="ctrl" class="generic-datasource-query-row" has-text-edit-mode="true">
 <div class="gf-form-inline">
 <div class="gf-form max-width-8">
 <select class="gf-form-input" ng-model="ctrl.target.type" ng-options="f as f for f in ['table', 'timeserie']"></select>
 </div>
 <div class="gf-form" ng-if="ctrl.target.rawQuery">
 <textarea class="gf-form-input" rows="5" ng-model="ctrl.target.tagkeys" spellcheck="false" ng-blur="ctrl.onChangeInternal()" />
 </div>

```
<div ng-if="!ctrl.target.rawQuery">
```

```
<div class="gf-form-inline">
<div class="gf-form">
```

```
<label class="gf-form-label query-keyword width-7">FROM</label>
<gf-form-dropdown model="ctrl.target.target"
allow-custom="true"
lookup-text="true"
get-options="ctrl.getMetrics($query)"
on-change="ctrl.onChangeInternal()">
</gf-form-dropdown>
</div>
```

```
<div class="gf-form">
<label class="gf-form-label query-keyword width-7">SELECT</label>
<gf-form-dropdown model="ctrl.target.tagkeys"
allow-custom="true"
lookup-text="true"
get-options="ctrl.getTags($tagkeys)"
on-change="ctrl.onChangeInternal()">
</gf-form-dropdown>
</div>
```

```
</div>
```

```
</div>
```

```
<div class="gf-form gf-form--grow">
<div class="gf-form-label gf-form-label--grow"></div>
</div>
```

</div>
</query-editor-row>

`

query_ctrl.js
`
import {QueryCtrl} from 'app/plugins/sdk';
import './css/query-editor.css!'

export class GenericDatasourceQueryCtrl extends QueryCtrl {

constructor($scope, $injector) {
 super($scope, $injector);

```
this.scope = $scope;
//this.target.target = this.target.target || 'select metric';
this.target.target = this.target.target || 'device';
this.target.tagkeys = this.target.tagkeys || 'parameter';
console.log("I am being erased", this.target.tagkeys);
//this.target.type = this.target.type || 'timeserie';
this.target.type = 'timeserie';
```

}

getMetrics(query) {
 //console.log(this.datasource.metricFindQuery(query || ''));
 return this.datasource.metricFindQuery(query || '');
 }

getTags(tagkeys) {
 //console.log(this.datasource.getTagKeys(tagkeys || ''));
 //console.log(this.target);
 return this.datasource.getTagKeys(tagkeys || '');
 }

toggleEditorMode() {
 this.target.rawQuery = !this.target.rawQuery;
 }

onChangeInternal() {
 console.log("might be here", this.target.tagkeys);
 this.panelCtrl.refresh(); // Asks the panel to refresh data.
 }
}

GenericDatasourceQueryCtrl.templateUrl = 'partials/query.editor.html';

`

Sorry for the bad formatting this is what is happening when pasting the code from the editor

**Comment by andig** [comment]
Without looking at your code- did you check the browser console?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
