### ISSUE TITLE
[Feature Request] ability to display the 'text' value (when /search returns map) in the table panel

### ISSUE THREAD

**Issue by rofran** [grafana/simple-json-datasource#106]
from https://github.com/grafana/grafana/issues/12697

I'm using extensively the Simple JSON Datasource plugin as a custom variable aliasing (with 
/search endpoints that returns { text: "label", value: "rawValue" } map responses).

I would like to use that functionality in the table panel. Currently I'm using the $tag_exampletag 
alias pattern in the "ALIAS BY" propierty which displays unfriendly ID codes. It would be 
possible to denfine a new "table panel alias pattern" which use the text of the "Value-to-text" Simple 
JSON Datasource template variables?
  
For example, being $tagname1 a simpleJSON datasource template variable, could be something similar
to $tagtext_tagname1[$tag_exampletag].

**Comment by andig** [comment]
Similar or extension of #101?

**Comment by rofran** [comment]
I guess it's not related. I don't use the /query endpoint (only the /search and /annotations endpoints).
In  place of the /query endpoint I use a influxdb datasource to populate a list of hosts (a list of 
ID host codes). Then using a simplejson template variable (/search enpoint) i get a friendly name of the
hosts. 

My feature request has to do with using the { text: "label", value: "rawValue" } of the simplejson template
variable in other parts of grafana, like in the table panel.

I resolved the issue using the column styles/value Mappings of the table panel and typing manually  
all host codes and its names. The ideal solution would be to use the { text: "label", value: "rawValue" }
mapping of the simplejson template variable in some way.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
