### ISSUE TITLE
Variable Value groups/tags

### ISSUE THREAD

**Issue by ausevj** [grafana/simple-json-datasource#108]
I can't get Value groups/tags (http://docs.grafana.org/reference/templating/#value-groups-tags) to work - not sure if it is implemented or not. The closest thing I found was "Tag Keys API" and "Tag Values API" which is used for `ad hoc` type queries. The problem is Value groups/tags use `/search` API not `/tag-keys` or `/tag-values`.

Data to reproduce (not posting the queries itself as that should not be relevant):

**Main query** returning:
```
[{"text": "To Do", "value": 1}, {"text": "In Progress", "value": 2}, {"text": "Done", "value": 2}]
```

**Tags query** returning:
```
["default"]
```

**Tag values query** returning:
(tried all of these)

1. `[1,2]`
2. `["To Do", "In Progress"]`
3. `[{"text": "To Do", "value": 1}, {"text": "In Progress", "value": 2}]`
4. `[{"type": "string", "text": "To Do"}, {"type": "string", "text": "In Progress"}]`
5. `[{"type": "string", "text": 1}, {"type": "string", "text": 2}]`

None of this works as expected - selecting 'default' label should select 'To Do' and 'In Progress' values, instead - label becomes inactive and value selections do not change.
I validated that queries do go through and reach grafana with forementioned values.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
