### ISSUE TITLE
[Feature request] Support jq-like data extraction

### ISSUE THREAD

**Issue by andig** [grafana/simple-json-datasource#111]
simple-json-datasource is great but depends on tailored backend JSON data sources. Any deviation from expected JSON schema won't work.

My proposal is to support something like the jq query and transformation language (https://stedolan.github.io/jq/tutorial/). Preferably during datasource definition, it should be possible to specify a jq transform per internal API (i.e. for `query`, `search` etc).

To keep things simple the execution could be handled by the proxy backend shelling out to jq instead of reimplementing it in the frontend.

I'd be happy to support with the back part if we can find anybody to support with frontend/ux.

**Update**: it looks like https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go might be a good place to start for implementing the backend side.

**Comment by andig** [comment]
This https://github.com/fiatjaf/jq-web should help a lot- jq cross-compiled to js using emscripten.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
