### ISSUE TITLE
simple-json-datasource abandoned?

### ISSUE THREAD

**Issue by andig** [grafana/simple-json-datasource#112]
@daniellee there are a couple of open PRs that would be interesting to merge and have not received any feedback since end of June. Could you please advise if this can be expected or if we should aim at forking this repo?

/cc @torkelo the various issues that have referenced this data source

**Comment by andig** [comment]
For all interested: we have grown impatient and started an experimental fork at https://github.com/simPod/grafana-json-datasource. We will not provide support for simple json issue but will focus on implementing new features that are helpful for the use cases at hand.

**Comment by daniellee** [comment]
The whole point of simple-json-datasource is to be forked (and that it is simple and not so feature rich) so please feel free to create a not-so-simple-json-datasource. It is the basis for lots of external plugins. If you want to build a more advanced version that would be great.

I'm the only one currently reviewing issues and PR's for a whole bunch of plugins and I've been on vacation. So these are on my todo list to review but are behind some of the other plugins and Grafana PR's in my review queue.

**Comment by simPod** [comment]
Thanks for reply! We have spun off our fork and are working on it to push things forward. We're not targeting any hard core features but well, there are some basic functionalites that makes json datasource much more powerful.

**Comment by daniellee** [comment]
This plugin is not abandoned - it is meant to be a simple example that is easy to fork and for you to do your own thing. For simple things, it does what it is supposed to do. Therefore I am closing this issue.

**Comment by inad9300** [comment]
@daniellee

Alas, this plugin is abandoned. It was only after lots of fighting with the plugin and its terrible documentation that I found the "no longer maintained" notice in the README in GitHub. Please, add this notice in the official plugin's page too!

**Comment by simPod** [comment]
You can use https://grafana.com/grafana/plugins/simpod-json-datasource/. It's alive.
