### ISSUE TITLE
Build fails on Windows due to non-portable path in package.json / scripts

### ISSUE THREAD

**Issue by Mariano76** [grafana/simple-json-datasource#113]
Build fails on Windows:

    C:\Utils\grafana-5.2.2\data\plugins\grafana-simple-json-datasource>npm run build
    
    > grafana-simple-json@1.0.0 build C:\Utils\grafana-5.2.2\data\plugins\grafana-simple-json-datasource
    > ./node_modules/grunt-cli/bin/grunt
    
    "." non è riconosciuto come comando interno o esterno,
    un programma eseguibile o un file batch.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! grafana-simple-json@1.0.0 build: `./node_modules/grunt-cli/bin/grunt`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the grafana-simple-json@1.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?
    
    npm ERR! A complete log of this run can be found in:
    npm ERR! C:\Users\....\AppData\Roaming\npm-cache\_logs\2018-08-28T12_40_57_294Z-debug.logAs suggested in https://github.com/npm/npm/issues/4040#issuecomment-27159695, I solved by changing non-portable paths in package.json from

```
"scripts": {
"build": "./node_modules/grunt-cli/bin/grunt",
"test": "./node_modules/grunt-cli/bin/grunt mochaTest"
},
```

to

```
"scripts": {
"build": "grunt",
"test": "grunt mochaTest"
},
```

Please test on other platforms and fix.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
