### ISSUE TITLE
Change query type named "timeserie" to "timeseries"

### ISSUE THREAD

**Issue by Jonnymcc** [grafana/simple-json-datasource#114]
I believe this is a typo. Unless there is justification for keeping it as "timeserie" I feel that it should be changed to "timeseries".
![screen shot 2018-09-18 at 12 00 29 pm](https://user-images.githubusercontent.com/1041598/45700477-a83f0600-bb3a-11e8-97e8-ee6bc552175e.png)

**Comment by stevenvachon** [comment]
I think it should be "datapoint", as it appears to be singular. It'd also be consistent with `maxDataPoints`.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
