### ISSUE TITLE
Why I get empty array for the '/annotations' request 

### ISSUE THREAD

**Issue by 2ur1st** [grafana/simple-json-datasource#116]
Plugin version '1.4.0'
Grafana version: Grafana Cloud

I set up plugin and connect to my server. Connect is success.
Next create a graph with new connection. 
Method `/search` work fine, I get all my targets, example
```
[
    {"text": "upper_125",  "value": 1},
    {"text": "upper_150",  "value": 2},
    {"text": "upper_175",  "value": 3},
    {"text": "upper_190",  "value": 4},
    {"text": "upper_195",  "value": 5}
]
```
But I did not see in my logs file any requests to `/annotations` or `/query`

I open console to check error and find that
<img width="842" alt="2018-10-31 15 02 11" src="https://user-images.githubusercontent.com/4361999/47786805-fe988a80-dd1d-11e8-9731-0cd63e27398b.png">
Why the response is empty array ?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
