### ISSUE TITLE
Node engine update

### ISSUE THREAD

**Issue by faiq** [grafana/simple-json-datasource#117]
Currently in the package.json its specified to use node 6.10.0. and both node 8.x and 10.x are LTS. I was able to build the application with node v8.11.4, so is this a strict requirement? I was able to successfully build and run the app by changing the engine in the `package.json` to 

```json
"engines": {
"node": ">6.10.0"
}
```

I can submit a pull request if node 6.10.0 is not a strict requirement

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
