### ISSUE TITLE
Question regarding HTTP Methods

### ISSUE THREAD

**Issue by stuartnelson3** [grafana/simple-json-datasource#12]
I'm curious what the rationale is behind using `POST` for the non-test endpoints: `/annotations`, `/query`, and `/search`? The issue arose because a proxy we're using defaults to blocking `POST`, and it seems a bit odd that endpoints that are attempting to gather data are not using `GET`.

**Comment by bergquist** [comment]
@stuartnelson3 that's a good question. TBH I dislike dealing with arrays (query targets) as parameters in querystrings. Languages deal with it so differently. (http://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys) 
My thinking was that people would find it easier and quicker to implement POST handler with json. 

Looking at graphite, opentsdb, influxdb and prometheus they use both POST and GET for metrics queries. 

Does it make sense?

**Comment by stuartnelson3** [comment]
Yeah, I think given the structure of the data being sent a `POST` is more convenient to work with, but the semantics of querying makes me think "ah that should be a `GET`".

Thanks for the answer!
