### ISSUE TITLE
Invalid url in query 

### ISSUE THREAD

**Issue by jgomezlopez** [grafana/simple-json-datasource#120]
Hey guys,

I created new simplejson datasource setting as url http://192.168.1.40:9080 and Server as access.
the url is accessed when test and save the datasource.
When I create a new pannel I can see the timeseries and I also see the request in the REST API server side, but I can't see any data in the graph. 
I checked the query inspector and I see url:"api/datasources/proxy/2/query" instead of url:"http://192.168.1.40:9080/query". The response is "Could not find a matching route". 

Any clue what I'm doing wrong?

Thanks in advance for your help.

Regards,

Jose

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
