### ISSUE TITLE
Can I use multiple option?

### ISSUE THREAD

**Issue by kdh0981** [grafana/simple-json-datasource#121]
Hi.
I am a developer using Grafana in Korea.
First, thank you for providing a good plugin.

I have one question.
The current version seems to offer only one option.
but, I want to use multiple depth options.
Is it possible in the current version?

Thank you.

![image](https://user-images.githubusercontent.com/14309428/52466957-42c1e380-2bc7-11e9-8a2b-5b7357f8cc4e.png)

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
