### ISSUE TITLE
Missing 'tag-key', 'tag-value'  selection in body parameters for the second '/tag-keys', 'tag-values' POST request

### ISSUE THREAD

**Issue by Helene** [grafana/simple-json-datasource#122]
Hello,
based on 'fake-simple-json-datasource' example I would like to apply multiple tag-key : tag-value attributes to the ad-hoc filter:
[{ 'key':'Country','value':'DE'},{ 'key':'City','value':'Berlin'}]
To do it, I need all selected tag-keys, tag-values included in the request body.

![image](https://user-images.githubusercontent.com/22845495/53604392-a29f1f00-3bb4-11e9-9b57-955fe8660d1d.png)

![image](https://user-images.githubusercontent.com/22845495/53604440-cebaa000-3bb4-11e9-9bf0-5d06e96a6bea.png)

![image](https://user-images.githubusercontent.com/22845495/53604510-fdd11180-3bb4-11e9-9df9-ea90c519bad4.png)

![image](https://user-images.githubusercontent.com/22845495/53604578-26590b80-3bb5-11e9-8cff-cc8b791e8885.png)
![image](https://user-images.githubusercontent.com/22845495/53604691-818afe00-3bb5-11e9-896c-d82da42604c4.png)
![image](https://user-images.githubusercontent.com/22845495/53604440-cebaa000-3bb4-11e9-9bf0-5d06e96a6bea.png)

At this point expecting the selection {key: 'Country', value: 'DE'} included in the '/tag-keys'  body request

![image](https://user-images.githubusercontent.com/22845495/53604174-0117cd80-3bb4-11e9-8858-30d21a454842.png)

![image](https://user-images.githubusercontent.com/22845495/53604303-52c05800-3bb4-11e9-957d-ea16db1ff1b4.png)

Also '/tag-values' request should include {key: 'Country', value: 'DE'} in the  body params

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
