### ISSUE TITLE
Help with singlestat  value

### ISSUE THREAD

**Issue by vovanb** [grafana/simple-json-datasource#123]
Hi
I am new to graphana... I have installed (https://github.com/bergquist/fake-simple-json-datasource) fake datasource.
I want to create simple dashboard using table from fake example:
[{"columns":[{"text":"Time","type":"time"},{"text":"Country","type":"string"},{"text":"Number","type":"number"}],"values":[[1553027298855,"SE",123],[1553026298855,"DE",231],[1553025298855,"US",321]]}]
I want to create singlestat panel http://docs.grafana.org/features/panels/singlestat/ using data from above table for example show Country = DE, so panel will show Number - 231.

In addition when I select table I got "Cannot read property 'length' of undefined" error ..
Will appreciate for help - may be possible to run short session

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
