### ISSUE TITLE
## Problem with search API, per documentation I am passing text and value mapping:

### ISSUE THREAD

**Issue by mrvic** [grafana/simple-json-datasource#124]
## Problem with search API, per documentation I am passing text and value mapping:
`[ { "text" :"upper_25", "value": 1}, { "text" :"upper_75", "value": 2} ]`

 **But dropdown metric control only shows text?**

 **Where are the values?**
 
![image](https://user-images.githubusercontent.com/6241361/55472862-6c1e4f00-560d-11e9-86d0-96bb99902116.png)
![image](https://user-images.githubusercontent.com/6241361/55472936-9bcd5700-560d-11e9-993d-9b7469b694c2.png)

_Originally posted by @mrvic in https://github.com/grafana/simple-json-datasource/issues/101#issuecomment-479435182_

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
