### ISSUE TITLE
Documentation for Grafana Templating Using SimpleJSON

### ISSUE THREAD

**Issue by spirited-ghosti** [grafana/simple-json-datasource#128]
I'm really new to this so maybe I'm just missing something but I cannot find the documentation of query formats for the variable feature in grafana. Any help with figuring out how to use it would be appreciated but the README only mentions the feature, not how to use it.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
