### ISSUE TITLE
save method and test method does nothing, causes entire server to get stuck

### ISSUE THREAD

**Issue by ekfliu** [grafana/simple-json-datasource#13]
created a datasource, attempts to edit the data source with save button or test button results in no feedbacks what so ever. Nothing on the server log or browser log, after pressing the save button and test button 10+ times the entire server locks up and have to be restarted.

Supposedly when pressing the test button the datasource.testDatasource() should be called but that is not the case. logs and debug indicate this method is never called.

**Comment by bergquist** [comment]
@ekfliu what version of grafana are you using?

**Comment by ekfliu** [comment]
The issue is fixed, it used to work with beta 5 but with beta 6 the query editor must use query-ctrl instead of ctrl.
