### ISSUE TITLE
Table with query editor

### ISSUE THREAD

**Issue by wernerdaehn** [grafana/simple-json-datasource#131]
If I am not mistaken, in the simple-json-datasource there is no way to control the fields and formulas used to return the data.
I select as target a single metric, that table has 300 columns. As I don't know which column the user is interested in, the backend would have to return all 300. In fact, I would not even return the requested measure only but all attributes and measures of that table!

Am I missing something or is this a valid request, to provide some sort of query editor in this datasource also?

**Comment by gjask** [comment]
There kinda is. The `Additional JSON Data` button shows text-field enabling you to specify arbitrary json structure, which gets sent to your backend. You can use it to specify columns to return for example.

Or as I do, to provide whole SQL query. :smirk: 
![Screenshot_2019-11-19 TEST - Grafana(1)](https://user-images.githubusercontent.com/3306648/69171245-dd0e6a80-0afb-11ea-981b-132ba018b2b7.png)

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
