### ISSUE TITLE
/search should distinct between timeseries and table

### ISSUE THREAD

**Issue by wernerdaehn** [grafana/simple-json-datasource#132]
What value do you return for a timeseries search request? CPU utilization, memory consumption and other measures.
What values do you return when somebody asks for a table? A tablename!!!

But the /search call does not provide the information if the user is searching for a metric or a table.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
