### ISSUE TITLE
[Question/Feature Request] change targets name in query response 

### ISSUE THREAD

**Issue by mjchl** [grafana/simple-json-datasource#135]
Is it possible to query a target so that the response shows a different name for Grafana to display?
Something like SELECT target AS humanReadableTitle in SQL.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
