### ISSUE TITLE
Intermittent Metric Request Errors

### ISSUE THREAD

**Issue by colsieb** [grafana/simple-json-datasource#136]
Firstly, kudos to the team!

Issue is that I seem to be having occasional errors getting data from the api that I have developed.  It works for the most part but If I have a dashboard open, every 10 or 15 minutes or so grafana starts getting metric request errors for all query requests.  This goes on for a few minutes then resumes normal operation without any intervention.
I am getting HTTP 500 errors returned on all query requests and the errors logged in the syslog of the hosting server are:

_t=2019-09-27T09:38:11+0100 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unknown desc = Post http://server/grafana_api/query: dial tcp 127.0.1.1:80: connect: connection refused_

During the outage I have tested the api with Postmaster and it is almost certainly reachable and returning the correct data from the network.  API logs also show that the endpoints are not even getting any requests so the issue surely has to lie with grafana and how it binds to localhost to get the data?

Any thoughts or anywhere else I could look for diagnostic information? Looking through browser dev info does not seem to reveal anything other than the http500 error.

simpleJSON 1.3.5 Backend Updated Fork
Grafana 6.2.5
Debian 9.0 Stretch

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
