### ISSUE TITLE
How to create backend URL's? 

### ISSUE THREAD

**Issue by arzWZM** [grafana/simple-json-datasource#137]
Your backend needs to implement 4 urls:

/ should return 200 ok. Used for "Test connection" on the datasource config page.
/search used by the find metric options on the query tab in panels.
/query should return metrics based on input.
/annotations should return annotations.

I don't understand how to do that. Can someone explain?

I want to implement this for zabbix and can't find any online articles who have already tried simple-json-datastore with zabbix

**Comment by jameskirsop** [comment]
Hi @arzWZM, if you're wanting to use Zabbix with Grafana, why not use the [Zabbix datasource plugin](https://github.com/alexanderzobnin/grafana-zabbix/)?

**Comment by nax3n** [comment]
I have the same problem, i am trying to display query from Ansible AWX but none of theses urls exists, is it possible to modify them ? 

Here is the API REST page of Ansible AWX :
![image](https://user-images.githubusercontent.com/32707825/80380597-12d03000-88a0-11ea-92f4-6500bd23a08e.png)

**Comment by birdayz** [comment]
you have to implement an application with this exact http interface.

**Comment by nax3n** [comment]
lol

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
