### ISSUE TITLE
Plugin not working - latest Grafana and Windows 10Pro

### ISSUE THREAD

**Issue by jinx17** [grafana/simple-json-datasource#141]
Hi,
I found out Simple Json plugin is not working on Grafana v6.4.3 on Windows10Pro.
I installed with grafana-cli, which resulted successfully.
Restarted service, but plugin is not working.

I also installed JSON datasource with success, and it is working.
Best regards,
Gregor

**Comment by coolxv** [comment]
the same of problem in grafana v6.5.1 on linux(Standalone Linux Binaries).
Error: Unexpected token '<' Evaluating http://192.168.224.19:3000/public/app/plugins/datasource/grafana-simple-json-datasource/module Loading app/plugins/datasource/grafana-simple-json-datasource/module

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
