### ISSUE TITLE
annotations doesnt requested

### ISSUE THREAD

**Issue by vinnitu** [grafana/simple-json-datasource#142]
Hi

I use 6.4.4 grafana and 1.4.0 simple-json-datasource.

But I doesn't see any request on annotations to datasource only /search and /query.

Why?

**Comment by cokeSchlumpf** [comment]
Might be a bit late, but I also just had the same question: You need to configure the dashboard to request annotations from your data source (as described here: https://grafana.com/docs/grafana/latest/reference/annotations/)

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
