### ISSUE TITLE
Variables is not being forwarded to target URL

### ISSUE THREAD

**Issue by davibaldin** [grafana/simple-json-datasource#143]
Hi,

When my Dashboard have variables, those variables are not being forwarded to the target URL server. For example:

http://192.168.57.225:3000/d/6VeKhk1Zz/inventory?orgId=1&var-InventoryType=activeDirectoryGroup&var-search=teste

I would like to my URL Backend receive those var-InventoryType=activeDirectoryGroup and var-search=teste Query parameters.

I'm using Server access mode.

My HTTP URL (Backend) is: http://192.168.128.11:8181/siteview/api/grafana

Is this configurable?

Thanks,

Davi

**Comment by abdulgalimov** [comment]
I have the same problem. Is there a way to fix it?

**Comment by davibaldin** [comment]
Hi, I couln't fix it and then, I moved to another solution.

Em sáb., 3 de out. de 2020 às 09:42, Zaur <notifications@github.com>
escreveu:

**Comment by abdulgalimov** [comment]
I fixed it https://github.com/grafana/simple-json-datasource/pull/163

**Comment by mellieA** [comment]
@grafana/grafana-edge-squad I noticed this external PR when triaging https://github.com/grafana/simple-json-datasource/issues/185

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
