### ISSUE TITLE
Unable to work under 'npm run build' command in Grafana env

### ISSUE THREAD

**Issue by Sunzhuoyi** [grafana/simple-json-datasource#144]
Error executing  "npm run build" command, Perhaps some of the installation packages for Babel are out of date.
Above problem will only in grafana/data/plugins/simple-json-datasource path execution, if it is independent clone execution does not have this problem.

**Comment by perfey** [comment]
You better use yarn. `yarn install --pure-lockfile`.  Then `yarn build`.
You could have a try.

**Comment by Sunzhuoyi** [comment]
@perfey, I'll try later.

**Comment by Sunzhuoyi** [comment]
@perfey Thanks. It works.
