### ISSUE TITLE
Configure with Bearer Token

### ISSUE THREAD

**Issue by mmaier2** [grafana/simple-json-datasource#146]
Hi,

I haven't so far found a way or guideline how to configure the simple datasource passing a defined Bearer Token for authentication. Not an API-Key or whatever - I want to specify my own token somewhere, so if I have to hardcode a token somewhere that would also be ok.

In curl you would do sth. like 
```
curl -H "Authorization: Bearer ${TOKEN}" ....
```

Thanks for your help
Markus

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
