### ISSUE TITLE
Bug: Wrong variable request

### ISSUE THREAD

**Issue by HaaLeo** [grafana/simple-json-datasource#147]
When creating a _Query_-variable with this plugin, the datasource sends a `/search` instead of a `/query` request. 
I filed an issue with more details in simPod/grafana-json-datasource#73

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
