### ISSUE TITLE
Ability to turn off proxy headers

### ISSUE THREAD

**Issue by jceddy** [grafana/simple-json-datasource#148]
Currently when I am creating a new dashboard using a simple-json-datasource data source, the plugin is attaching proxy headers (like X-Forwarded-Path) to the request it is sending to my JSON api. My application uses this header for a very specific purpose and it causes an error when included on these requests.

Is there a way to disable these headers?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
