### ISSUE TITLE
This is not defined when using short function syntax in JS

### ISSUE THREAD

**Issue by SamMousa** [grafana/simple-json-datasource#149]
I'm receiving some errors in my JS console and traced them back to this line:

https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L112

```js
 var targets = _.map(options.targets, target => {
      return {
        target: this.templateSrv.replace(target.target, options.scopedVars, 'regex'),
        refId: target.refId,
        hide: target.hide,
        type: target.type || 'timeserie'
      };
    });
```

This same pattern occurs multiple times in that same file and some have been in there for 4 years. Was there maybe some change in the preprocessing of the javascript?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
