### ISSUE TITLE
Readme hyperlink is broken for document referer

### ISSUE THREAD

**Issue by cysk92** [grafana/simple-json-datasource#151]
docs link points to a URL that no longer exist in the readme:

Simple JSON Datasource - a generic backend datasource
More documentation about datasource plugins can be found in the Docs.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
