### ISSUE TITLE
Update docs: RefId needs to be passed to result for filter by transformation to work

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/simple-json-datasource#164]
We are not passing refId to result and therefore transformation filter by query does not work. 
More info https://github.com/grafana/grafana/issues/28373

**Comment by MatinF** [comment]
Any updates on this?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
