### ISSUE TITLE
Trying to retrieve tag keys dynamically.

### ISSUE THREAD

**Issue by jonelkhoury** [grafana/simple-json-datasource#165]
Hi y'all, I've been trying to retrieve tag-keys dynamically based on the dashboard and data being shown. I currently have dashboards with different datasets and I'm attempting to pull possible tag-keys based on the columns in each dataset. I'm struggling to do so right now and was wondering if there's anyway to modify the tag-keys request to return the dashboard/panel IDs to my API?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
