### ISSUE TITLE
return tag-values depends on selected value of other tags

### ISSUE THREAD

**Issue by smartgear** [grafana/simple-json-datasource#166]
I'm trying to add an ad-hoc filter for a dashboard.
There will be several variables in the filter, e.g. service, sub-service.
I want to provide options of "sub-service" depending on the value of "service". Indeed I hope to get a parent-child drop down list.
Currently, when I implement /tag-values, the only information I can get from the request is the key of tag.
Can the selected value of other tag be put in the request as a context?
Thanks!

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
