### ISSUE TITLE
HTTP Error Bad Request

### ISSUE THREAD

**Issue by VinayDanda** [grafana/simple-json-datasource#167]
Trying to create a datasource with type SimpleJson.
Specifying HTTP url: http://<host>:5003
Saving it shows "HTTP Error Bad Request"

The url is accessible from the grafana instance, and don't understand why the error is coming.
Can you please suggest.

![image](https://user-images.githubusercontent.com/33858700/99030934-d80fba00-259b-11eb-89c9-a95b70aded7c.png)
![image](https://user-images.githubusercontent.com/33858700/99030638-8c5d1080-259b-11eb-985f-c367e0a0459c.png)

**Comment by indran-dados** [comment]
We are having the same issue, we have tried installing and reinstalling both grafana and the plugins :(

**Comment by byteptr** [comment]
I have error 400 
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>400 Bad Request</title> <h1>Bad Request</h1> <p>Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)</p>`
I am using grafana 8.8.3

**Comment by amotl** [comment]
Hi @VinayDanda, @indran-dados and @byteptr,

following up on @byteptr's report at https://github.com/panodata/grafana-pandas-datasource/issues/7, we wanted to also share our insights here, about how we solved the problem.

### Problem and solution
The problem you are observing
> happens because the Simple JSON Datasource might send upstream HTTP requests with empty request bodies, but still with the `Content-Type: application/json` HTTP header present. Some web frameworks do not handle that well and will attempt to decode the empty string from JSON, which will just croak.

At https://github.com/panodata/grafana-pandas-datasource/issues/7#issuecomment-1030044581, we shared more details about this in the context of the Flask web framework. https://github.com/panodata/grafana-pandas-datasource/pull/10 provides an easy patch to improve the situation and we will be happy to hear back from @byteptr about the outcome there.

### Enquiry
Now, already knowing that @byteptr _actually wanted_ to use `grafana-pandas-datasource` in this context, where this issue has been mitigated now, I would be curious about the HTTP upstream services used by @VinayDanda and @indran-dados in their installations: Maybe you can share the information about the kind and version of the web framework you are using on your end? Thanks in advance!

### Thoughts
That being said, it probably would not hurt if Simple JSON Datasource would stop sending `Content-Type` headers on requests with zero content, and specifically on all GET requests to the upstream HTTP endpoint(s).

With kind regards,
Andreas.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
