### ISSUE TITLE
get value of RefreshPicker

### ISSUE THREAD

**Issue by sagisd** [grafana/simple-json-datasource#168]
Hi, 
I have two questions:
1. how can I get the value of RefreshPicker?
2. how can I detect click on the refresh icon?

I need to know when /query need to ask the backend for a new data

![image](https://user-images.githubusercontent.com/64784301/102896311-d8d71e00-446e-11eb-8dbe-05ecfd0cd65c.png)

Thanks!

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
