### ISSUE TITLE
Simple JSON data source kills CSVServer

### ISSUE THREAD

**Issue by wonkert** [grafana/simple-json-datasource#169]
Upgraded from 6.5 to 7.3 and have an issue with the JSON data plugin and CSVServer.  

When adding a new panel and configuring the json data source, there is an exception thrown in the CSVServer.  Having had an initial look the CSV Server is being called with a blank target defined in the POST to query.  In turn, this results in CSV server trying to load the ./csv directory as a CSV file (rather than accessing a CSV in the directory)

Grafana : 7.3.6
JSON Data Source : 1.4.1

Presume this is down to a change in the way plugins work for 7.3?  there doesn't appear to be a call to get a list of CSV files before the query to load a CSV file.

output from the failing process as follows.

[1608727720751] INFO  (26220 on ************): incoming request
    reqId: 3
    req: {
      "method": "POST",
      "url": "/query",
      "hostname": "127.0.0.1:4000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 54740
    }
/query
body={"app":"dashboard","requestId":"Q112","timezone":"browser","panelId":23763571993,"dashboardId":42,"range":{"from":"2020-12-23T11:48:40.738Z","to":"2020-12-23T12:48:40.738Z","raw":{"from":"now-1h","to":"now"}},"timeInfo":"","interval":"2s","intervalMs":2000,"targets":[{"target":"","refId":"A","type":"timeserie"}],"maxDataPoints":1650,"scopedVars":{"__interval":{"text":"2s","value":"2s"},"__interval_ms":{"text":"2000","value":2000}},"startTime":1608727720740,"rangeRaw":{"from":"now-1h","to":"now"},"adhocFilters":[]}
target[0]
{ target: '', refId: 'A', type: 'timeserie' }

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event at:
    at lazyFs.read (internal/fs/streams.js:165:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)

**Comment by wonkert** [comment]
I should have added.  Existing panels work just fine, it's only where a new panel is being added and the user attempts to select the CSV to use for a series.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
