### ISSUE TITLE
Changed Metrics List behavior makes Metrics unusable

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/simple-json-datasource#171]
Hi!
Since I am not sure whether this issue belongs to Grafana (https://github.com/grafana/grafana/issues/30679) or to simpod-json-datasource, I post an own issue here as well.

Please kindly investigate it.

**What happened**: Metrics list stops working, freezes with larger amount of metrics

**What you expected to happen**: Metrics list does not freeze and allows to load portions of the metrics based on the text entered.

**How to reproduce it (as minimally and precisely as possible)**:
Connect to a database with over 100.000 Metrics. Grafana will try to load all metrics at once and populate some sort of cache. Due to the large amount of Metrics, this will take much longer and makes the list instable.

**Anything else we need to know?**:
In 6.7.3 Grafana Version with simpod-json-datasource 0.1.8.0 everything worked fine:
On each key entry the Metrics List run a new query against the DataSource. That allowed us to limit the number of items returned with one query and let the user select the desired name by entering more and more characters.

Without this behaviour we cannot limit the list of returned metrics resulting from api/datasources/proxy/2/search/ query and as such the whole system becomes instable / unsable.

Please kindly add a configuration possibility to enforce the previous "each key entry runs its own search query" behavior.

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: https://grafana.com/grafana/plugins/simpod-json-datasource 0.2.3.0
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
