### ISSUE TITLE
operations on values

### ISSUE THREAD

**Issue by SledgehammerPL** [grafana/simple-json-datasource#18]
Is it possible (or how) to get avg of three values received by simple-json-datasource? On graphite datasource after the choosing the target man can make some operations on value (even setting alias name).

**Comment by bergquist** [comment]
simple-json-datasource does not do any calculations. That's up to the datasource to support.

**Comment by SledgehammerPL** [comment]
You misunderstand - I can preprare datasource, but don't know how to pass information from datasource to grafana via simple-json-datasource, that datasource CAN send some calculations. For now I just add one more value named avg(something) but it appears just like other values. I want to choose value, than choose calculation,
