### ISSUE TITLE
adding npm libary to dependencies

### ISSUE THREAD

**Issue by LaPush** [grafana/simple-json-datasource#19]
I used the simple-json-datasource Plugin and added the mqtt library [github.com/mqttjs/MQTT.js](url)
like so:

I ran `npm install mqtt --save` in the simple-json-datasource folder, so it would be in the package.json as a dependency.

in the datasource.js I added:
```
import mqtt from "mqtt";
```
afterwards I ran the grunt task which build the src files to the dist folder.

I also ran `npm install mqtt --save` in the grafana folder and ran the grunt task there also,
but I always get the following error when I try to add my simple-json-datasource Plugin:

> Plugin Error
> Error loading http://localhost:3000/public/mqtt as "mqtt" from http://localhost:3000/public/plugins/grafana-simple-json-datasource/datasource.js

I cant figure out how to add a external library to the datasource Plugin and get it running, do I miss out something?

I would be very thankful for some help or advice on how to use npm libraries which arent included in grafana by default. I couldnt find any information regarding that matter.

**Comment by bergquist** [comment]
When running npm install you will download that package into node_modules. Which is not available for grafana. To use npm packages you need to first download them and then copy them from node_modules to the rootfolder/dist folder.

**Comment by LaPush** [comment]
By rootfolder/dist folder you mean "github.com/grafana/grafana" ?
Because in this folder it still doesnt work. Could you please give me a clue where to put the node module folder, im working on this for days and cant figure it out...

Hope i didnt bother you

**Comment by Madhu94** [comment]
@LaPush, did  you figure it out? I'm having the same issue.

**Comment by aksakalli** [comment]
@LaPush I came across the same issue with including additional dependency. I used this experimental plugin as boilerplate to tackle this issue: https://github.com/NatelEnergy/grafana-plotly-panel/

1. You need to create a folder: `src/external/`
2. Add the compiled single file dist versions of your dependency under this folder like `src/external/mqtt.js`. (Actually even Grafana project has vendors in git repository https://github.com/grafana/grafana/tree/master/public/vendor)
3. In build task, you need to copy the files under your `external` folder, so your `Gruntfile.js` should be like:

```
module.exports = (grunt) => {
  require('load-grunt-tasks')(grunt);

  grunt.loadNpmTasks('grunt-execute');
  grunt.loadNpmTasks('grunt-contrib-clean');

  grunt.initConfig({

    clean: ['dist'],

    copy: {
      src_to_dist: {
        cwd: 'src',
        expand: true,
        src: ['**/*', '!**/*.js', '!**/*.scss', '!img/**/*'],
        dest: 'dist'
      },
      pluginDef: {
        expand: true,
        src: ['README.md'],
        dest: 'dist',
      },
      externals: {
        cwd: 'src',
        expand: true,
        src: ['**/external/*'],
        dest: 'dist'
      },
      img_to_dist: {
        cwd: 'src',
        expand: true,
        src: ['img/**/*'],
        dest: 'dist'
      }
    },

    watch: {
      rebuild_all: {
        files: ['src/**/*'],
        tasks: ['default'],
        options: {spawn: false}
      },
    },

    babel: {
      options: {
        sourceMap: true,
        presets: ['es2015'],
        plugins: ['transform-es2015-modules-systemjs', 'transform-es2015-for-of'],
      },
      dist: {
        files: [{
          cwd: 'src',
          expand: true,
          src: ['*.js'],
          dest: 'dist',
          ext: '.js'
        }]
      },
    },

  });

  grunt.registerTask('default', ['clean', 'copy:src_to_dist', 'copy:pluginDef', 'copy:img_to_dist', 'copy:externals', 'babel']);
};
```

4. Now you can import the external library: `import * as mqtt from './external/mqtt';`

**Comment by jinty** [comment]
I found this particularly tricky to figure out, so I made an example commit: see here https://github.com/jinty/simple-json-datasource/commit/3508ec86d6e5a2f76d1c3ae566caadc3d531e22b

it's not very nice, but does actually work

**Comment by allguitars** [comment]
I followed every step that @aksakalli  addessed. Now, there is no issue for imporint the module, but I got another issue.

I am using this [example code](https://github.com/grafana/simple-json-datasource) and revising it to include the functionality of **mqtt** module.

Here is my _datasource.js_

```
import * as mqtt from './external/mqtt';

export class GenericDatasource {
  ...

  constructor(instanceSettings, $q, backendSrv, templateSrv) {
      this.mqttUri = 'xxxxxxxxxxx'  // credentials for connecting to the message broker
      ...

      console.log('Constructor called!');
      console.log(this.mqttUri);

  }

  ...

  testDatasource() {

    console.log(mqtt.connect);

    // MQTT: connect and subscribe
    let client = mqtt.connect(this.mqttUri);
    client.on('connect', function () {
      client.subscribe('temp', function (err) {
        if (!err) {
          console.log('subscribed successfully.');
          // client.publish('temp', 'Hello mqtt');
        } else {
          console.log(err);
        }
      });
    });

    return this.doRequest({
      url: this.url + '/',
      method: 'GET',
    }).then(response => {
      if (response.status === 200) {
        return { status: "success", message: "Data source is working", title: "Success" };
      }
    });
  }


  ...

}

```


And here is the my _Gruntfile_.
```
module.exports = function (grunt) {

  require('load-grunt-tasks')(grunt);

  grunt.loadNpmTasks('grunt-execute');
  grunt.loadNpmTasks('grunt-contrib-clean');

  grunt.initConfig({

    clean: ["dist"],

    copy: {
      src_to_dist: {
        cwd: 'src',
        expand: true,
        src: ['**/*', '!**/*.js', '!**/*.scss'],
        dest: 'dist'
      },
      pluginDef: {
        expand: true,
        src: ['README.md'],
        dest: 'dist'
      },
      externals: {
        cwd: 'src',
        expand: true,
        src: ['**/external/*'],
        dest: 'dist'
      }
    },

    watch: {
      rebuild_all: {
        files: ['src/**/*'],
        tasks: ['default'],
        options: { spawn: false }
      }
    },

    babel: {
      options: {
        sourceMap: true,
        presets: ['es2015']
      },
      dist: {
        options: {
          plugins: ['transform-es2015-modules-systemjs', 'transform-es2015-for-of']
        },
        files: [{
          cwd: 'src',
          expand: true,
          src: ['**/*.js'],
          dest: 'dist',
          ext: '.js'
        }]
      },
      distTestNoSystemJs: {
        files: [{
          cwd: 'src',
          expand: true,
          src: ['**/*.js'],
          dest: 'dist/test',
          ext: '.js'
        }]
      },
      distTestsSpecsNoSystemJs: {
        files: [{
          expand: true,
          cwd: 'spec',
          src: ['**/*.js'],
          dest: 'dist/test/spec',
          ext: '.js'
        }]
      }
    },
    mochaTest: {
      test: {
        options: {
          reporter: 'spec'
        },
        src: ['dist/test/spec/test-main.js', 'dist/test/spec/*_spec.js']
      }
    }
  });

  // grunt.registerTask('default', ['clean', 'copy:src_to_dist', 'copy:pluginDef', 'copy:externals', 'babel', 'mochaTest']);
  grunt.registerTask('default', ['clean', 'copy:src_to_dist', 'copy:pluginDef', 'copy:externals', 'babel']);
};

```


Whenever I configure the SimpleJson data source in grafana and click the "Test & Save" button, I get the following error message.

```
mqtt.connect is not a function
```

Here is my console output. It shows that ``mqtt.connect`` is undefined.

```
Constructor called!
datasource.js:27 mqtt://xxxxx
datasource.js:54 undefined
```


Thanks in advance.
