### ISSUE TITLE
Problem with the Grafana's "Tooltip mode".

### ISSUE THREAD

**Issue by mbarragan** [grafana/simple-json-datasource#25]
I'm beginning using this Grafana plugin and I realised that if I display a Graph panel with the "Tooltip mode" set to "Single" the graph shows the information correctly, but if the "Tooltip mode" is set to "All series", is shown the same information for all the timestamps.

Tooltip mode = All series
![image](https://cloud.githubusercontent.com/assets/9413404/16913851/1564f252-4cee-11e6-85ce-20cb6dd46012.png)
![image](https://cloud.githubusercontent.com/assets/9413404/16913853/16cee080-4cee-11e6-8908-89e8eb9fce1c.png)

Tooltip mode = Single
![image](https://cloud.githubusercontent.com/assets/9413404/16913907/6bd7b606-4cee-11e6-808c-2ba20ca4f8d4.png)
![image](https://cloud.githubusercontent.com/assets/9413404/16913909/6df11d88-4cee-11e6-99e5-63d22bd2bee9.png)

In all the cases the response to the Query call is:

`[
  {
    "target": "xtg",
    "datapoints": [
      [
        1,
        1468582839280
      ],
      [
        2,
        1468582789280
      ],
      [
        3,
        1468582739280
      ],
      [
        4,
        1468582689280
      ],
      [
        5,
        1468582639280
      ],
      [
        6,
        1468582589280
      ],
      [
        7,
        1468582539280
      ],
      [
        8,
        1468582489280
      ],
      [
        9,
        1468582439280
      ],
      [
        8,
        1468582389280
      ],
      [
        7,
        1468582339280
      ],
      [
        6,
        1468582289280
      ],
      [
        5,
        1468582239280
      ],
      [
        4,
        1468582189280
      ],
      [
        3,
        1468582139280
      ],
      [
        1,
        1468582089280
      ]
    ]
  },
  {
    "target": "Response Time",
    "datapoints": [
      [
        200,
        1468582839280
      ],
      [
        220,
        1468582789280
      ],
      [
        190,
        1468582739280
      ],
      [
        188,
        1468582689280
      ],
      [
        300,
        1468582639280
      ],
      [
        500,
        1468582589280
      ],
      [
        488,
        1468582539280
      ],
      [
        300,
        1468582489280
      ],
      [
        256,
        1468582439280
      ],
      [
        196,
        1468582389280
      ],
      [
        200,
        1468582339280
      ],
      [
        202,
        1468582289280
      ],
      [
        230,
        1468582239280
      ],
      [
        211,
        1468582189280
      ],
      [
        199,
        1468582139280
      ],
      [
        254,
        1468582089280
      ]
    ]
  }
]`

**Note:** 
- I'm using Grafana version: 3.0.3
- I'm using SimpleJson plugin version: 1.1.0

Am I doing something wrong?

**Comment by dizzzz** [comment]
No I have seen the same behaviour. It is also in 1.1.2 (and 1.2.2)

**Comment by dizzzz** [comment]
Seems to be solved with grafana 3.1.0 and plugin version 1.2.2

**Comment by bergquist** [comment]
The datapoints should be in ascending order. 

The example app at https://github.com/bergquist/fake-simple-json-datasource have been corrected to use correct sort order.
