### ISSUE TITLE
Release of 1.2.2

### ISSUE THREAD

**Issue by dizzzz** [grafana/simple-json-datasource#26]
Please could you release 1.2.2 (or beyond) ?  And publish it via https://grafana.net/api/plugins/grafana-simple-json-datasource/versions/1.2.2/download ?

In addition it would be nice if you'd add a release to GitHub (it is a one-click-step, providing generated delta-info etc).

If you need help, I am happy to provide.

**Comment by bergquist** [comment]
1.2.2 and 1.2.3 have been released on grafana.net
Sorry for the delay
