### ISSUE TITLE
/search using tags issue

### ISSUE THREAD

**Issue by JKerwood** [grafana/simple-json-datasource#27]
Search works find for finding the names.  The examples have the response being a list of strings.  If you try to return a list and configure tags it doesn't work correctly.  It actually expects a map.  
I'd recommend either changing this code to handle a list vs a map or at least mention tags in the examples.

**Comment by argh** [comment]
I bumped into this as well on query templates.  The templating "preview of values" worked fine with a list, but when you actually selected a value it injected a number into the template expansion.  When I switched to returning a map, things started to work.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/simple-json-datasource/pull/36
