### ISSUE TITLE
Metric query does not substitute other templating variables in queries

### ISSUE THREAD

**Issue by 0x6373** [grafana/simple-json-datasource#29]
When using a templating variable to query a simple-json-datasource in another templating variable (so query will be something like "server.$servername.network.*") there is no substitution of the variable in the query.

Let's say we have a variable called "servername" which currently has the value "testserver1".
Now i want to have a list of network interfaces in another variable (for templating), so i would query the datasource with a query of "server.$servername".network.*".

With a graphite datasource the request sent to the backend is then "server.testserver1.network._", but with simple-json-datasource i get the following request: "server.$servername.network._".

I think "$servername" should be substituted, am i right?

**Comment by saboorian** [comment]
I think you are looking for nested templates #23

**Comment by bergquist** [comment]
closed by #23
