### ISSUE TITLE
How to make correct vertical scale?

### ISSUE THREAD

**Issue by tral** [grafana/simple-json-datasource#3]
Hello, I got the following situation:
http://dn.imagy.me/201602/18/2af0c9a822df45baffd1ef44de8fb92e.png
As you can see, lines don't fill all available vertical space.
We want it to looks like that: http://dn.imagy.me/201602/18/211924e91775d28edbcd4d1741b9d471.png
How can I achieve this? 
We're using this custom datasource.
Also we noticed that with other datasources scaling is correct.

**Comment by tral** [comment]
Any ideas?

**Comment by tral** [comment]
So, the problrm still remains in 3.0.0-beta1:
Full data, scale is OK: http://dn.imagy.me/201604/04/00a939443dd57c5ab86b3f1b2baffcad.png
Partial data, scale is not ok: http://dn.imagy.me/201604/04/b02556366d42fe1f4657a4103e8b9467.png

**Comment by tral** [comment]
Guys, maybe you can reproduce this?
I don't know if it's grafana's or plugin's bug, but it is definitely a bug!
You just need to install this plugin and use this datasource http://french.perm.ru/grafana
( http://french.perm.ru/grafana/search
http://french.perm.ru/grafana/query )

**Comment by bergquist** [comment]
@tral I cannot reproduce this error with my sample app. (https://gist.github.com/bergquist/bc4aa5baface3cffa109) Can you?

**Comment by tral** [comment]
it's ok now, you can close this issue, I've found the answer here: https://github.com/grafana/grafana/issues/4560
