### ISSUE TITLE
template for query type calls /search endpoint without passing "query"

### ISSUE THREAD

**Issue by argh** [grafana/simple-json-datasource#30]
As far as I can tell, there's no way to differentiate a "metrics name" search from a "template query" search because the "query" line is not passed to the endpoint.

Repro: 
1. Create new template
2. Set type "Query"
3. Set data source to your simple-json-datasource backend
4. Enter anything into "query"
5. Hit "Update".
6. Monitor the endpoint; nothing passed in query or in POST payload to differentiate from a metrics name search.

I was able to get around this by creating artificial datasources that pointed to custom paths that include the parameters I want to look for, but this is super clunky.

I think the "query" value should be POSTed to the /search, then we can use the same data source, and be able to perform different types of search.

My use case:

I have template queries that look like:

system/cpu/average where cluster=$cluster and role=$role by $interval

system/cpu/average where cluster=prod and role=frontend by minute

My /search on metric names expands to things like "system/cpu" or "orders/revenue".  But I want to be able to find all dimensions that match, so I'd like to have something in the "query" field like "cluster" which on the backend would find all samples with dimension cluster=(whatever) and return the list of unique (whatever)s.  So instead I have a custom backend route like "/grafana/dimensions/{dimension}/search" and have to create new data sources like "/grafana/dimensions/cluster" and "/grafana/dimensions/role".

**Comment by letonphat1988** [comment]
Hi argh,
Today I've had a issue like you. I couldn't see the post data at my api server, actually the grafana page didn't add it to the request's payload before. After few hours for debuging, I saw in the "simple-json-datasource/dist/datasource.js" file at line 108:
         key: 'metricFindQuery',
           value: function metricFindQuery(options) {
             var interpolated = {
              **_Line 108 ==> target: this.templateSrv.replace(options.target, null, 'regex')_**
             };
"options.target" always return null value and it was fine after i changed  "options.target" to "options"

I hope it's helpful and have someone understand and fix it permanently

**Comment by meverett** [comment]
+1

I just ran into this issue too. I needed to use this plugin to create a template query (that was in fact my main use case). I was really bummed when no values were coming through.

Here is my fix that seems to work and keep backwards compatibility starting on line 107 of datasource.js:

```
var interpolated = {
  target: this.templateSrv.replace(typeof (options) == "string" ? options : options.target, null, 'regex')
};
```

**Comment by meverett** [comment]
For what it's worth I've submitted a [pull request](https://github.com/grafana/simple-json-datasource/pull/36) that fixes this issue and as well as adding support for returning either a simple array/list of results or Grafana's supported nested text/value objects (so you can have a human-readable label but preserve the raw value).

**Comment by bergquist** [comment]
closed by https://github.com/grafana/simple-json-datasource/pull/36
