### ISSUE TITLE
README.md example objects appear to be out of date

### ISSUE THREAD

**Issue by pnzrdrgoon** [grafana/simple-json-datasource#33]
/query example
query object appears to no longer send an intervalMS
range object appears to no longer contain a raw object

**Comment by bergquist** [comment]
What grafana version are you running?

Grafana 3 and 4 should still send the intervalMS property
https://github.com/grafana/grafana/blob/master/public/app/features/panel/metrics_panel_ctrl.ts#L200

range.raw should also be available `range.raw` https://github.com/grafana/grafana/blob/master/public/app/features/panel/metrics_panel_ctrl.ts#L117
