### ISSUE TITLE
Support for Grafana 4.x.x

### ISSUE THREAD

**Issue by janhurst** [grafana/simple-json-datasource#35]
It appears that the Simple JSON datasource is not compatible with Grafana 4.x.x. It would be great to get it updated.

**Comment by bergquist** [comment]
@janhurst what error do you see? it works as expected for me.

**Comment by janhurst** [comment]
@bergquist the plugin appears to install but isn't visible in the list of available data sources. note I've only tried in 4.0.0. I will take a closer look as soon as I can get some time and report back

**Comment by janhurst** [comment]
@bergquist I spent some more time on this. I did a very clean install (unzip) of 4.0.1 and used the grafana-cli to install the simple-json-datasource. everything worked as expected. apologies for the possible dud issue report. either something was different in 4.0.0 and things are now all ok, or I screwed something up on my install

**Comment by bergquist** [comment]
@janhurst no worries! :)

**Comment by aplsek** [comment]
I have a problem with testing the the datasource with with Grafana 4.x.x.

I have installed the plugin by cloning the repo into the `$GOPATH/src/github.com/grafana/grafana/data/plugins/datasources`

**Comment by aplsek** [comment]
Ok, I have made some progress. The plugin works in the latest grafana, but when I want edit it and recompile it with `grunt` it fails with :

**Comment by aplsek** [comment]
So, it looks like the `Gruntfile.js` should be updated to include the `'transform-class-properties'` plugin in the `babel` task dependencies.

**Comment by bergquist** [comment]
Added 6.10.0 requirement to package.json.
If someone want to support nodejs 7+ please create a PR.

Also added note about using yarn instead of npm install.
