### ISSUE TITLE
Plugin with same id already exists

### ISSUE THREAD

**Issue by jangaraj** [grafana/simple-json-datasource#38]
Grafana logs:
```
t=2016-12-10T04:19:58+0000 lvl=info msg="Registering plugin" logger=plugins name=SimpleJson
t=2016-12-10T04:19:58+0000 lvl=eror msg="Plugins: Failed to load plugin json file: [/grafana-plugins/grafana-simple-json-datasource/dist/src/plugin.json Plugin with same id already exists],  err: %!v(MISSING)"
```
Problem is 2 identical plugin.json files:
```
dist/plugin.json
dist/src/plugin.json
```
`Gruntfile` should be updated to produce only one plugin.json in dist directory.

BTW: `raintank-worldping-app` plugin has the same problem

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/simple-json-datasource/commit/b4d955245aedb9a4243733626a715dfc58d9a694

**Comment by Accpet** [comment]
grafana-simple-json-datasource can you del?
