### ISSUE TITLE
Fancy metric selection

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/simple-json-datasource#40]
I'm wondering if we can make the metric selection work all fancy like with for example an influxdb datasource?
Is this implemented? How would one 'use' this?

I'm building a python server to work with the SimpleJSON plugin and thought that the '/search' query and returned data would achieve this but I can't get Grafana to fire any '/search' queries.

Thanks.

**Comment by ikkemaniac** [comment]
hmm ok.... I got things mixed up. I was convinced the '/search' request would be GET... but it's POST. It works now :)

ps. please use tags to mark releases

**Comment by simPod** [comment]
@daniellee can we close? :)
