### ISSUE TITLE
Nested templates interpolated the selection index instead of the selection text

### ISSUE THREAD

**Issue by johnrengelman** [grafana/simple-json-datasource#41]
Using 1.2.4 which includes this PR - https://github.com/grafana/simple-json-datasource/pull/23
However, when I have a template that includes another template value, it is interpolating in the template's index instead of the text.

Is there a way around this?

So I have variable `$team` which is being populated with simple-json-datasource with the data `["foo", "bar"]`.
Than I have a second variable `$services` which is setting it's value as this: `$.data.teams[?(@.name == $team})].services[*]` (it's a JSONPath selector.

but the resulting value sent in the POST is `$.data.teams[?(@.name == 1})].services[*]` 
when I expect it to be `$.data.teams[?(@.name == bar})].services[*]`

**Comment by johnrengelman** [comment]
Additionally, it appears that index [0] always uses the "text" value, because of the `metricNamesToVariableValues` function.

**Comment by VadimPulver** [comment]
Same here. If the result is returned in map format [{text: "foo", value: 1}], when the "value" is returned
