### ISSUE TITLE
Data Source Config

### ISSUE THREAD

**Issue by muschneider** [grafana/simple-json-datasource#43]
I'm trying configuring de SimpleJson DataSource in Grafana 4.1.1 and the "Unknown error" is showing when I click em "Save & Test". 

I can see Grafana doesn't call a root URL in "fake-simple-JSON-data source" to test.

**Comment by muschneider** [comment]
I just see that work with proxy in DataSource configuration. The problem is when choosing Direct in Connection.

**Comment by bergquist** [comment]
Make sure the datasource url does not end with an `/`

**Comment by muschneider** [comment]
I did a test with the URL ending up with a slash and without, both tests I'm getting "Unknown error" error when I choose direct as a connection. But with the proxy is working smoothly.

**Comment by bergquist** [comment]
This is probably due to missing `Access-Control-Allow-Origin` header on the server that simple json is trying to connect to.

**Comment by yadavs1310** [comment]
which file should Access-Control-Allow-Origin be set to .I am on apache
