### ISSUE TITLE
Query sending 'text' value from search map

### ISSUE THREAD

**Issue by chriscarpenter12** [grafana/simple-json-datasource#44]
Why is my query sending the 'text' value from the search map?

Search is returning:
`targets = [ { 'text' :'Renewed', 'value': 'renewed'}, { 'text' :'Expired', 'value': 'expired'} ]`

In the Metrics tab on the panel the `A` and `B` both show `Removed` and `Expired` as expected, but is sending this:
```
[ { "target": "Renewed", "refId": "A", "type": "timeserie" }, { "target": "Expired", "refId": "B", "type": "timeserie" } ]
```

Is this the desired behavior? I figured it would send the 'value' field from search?

**Comment by andig** [comment]
I cannot confirm this. Always get the value passed into query. Unfortunately replying with value also overrides the metric title in the chart.

**Comment by chriscarpenter12** [comment]
It’s been quite a while since I looked back at this. Going to close it for now if I’m the only one experiencing this issue.

**Comment by andig** [comment]
I do however have the problem with the `query` api here which seems loosely related
