### ISSUE TITLE
Is it possible to add support for alerts?

### ISSUE THREAD

**Issue by dumaal** [grafana/simple-json-datasource#46]
This datasource is incredibly versatile opening a way for Grafana to access virtually any data (cough IoT).
Alert support would be incredibly useful.

**Comment by bergquist** [comment]
That would require https://github.com/grafana/grafana/issues/6841 to be implemented first.

**Comment by lgunnar** [comment]
How far into the future do you think this feature is? I'd really love to have it, but since the issue grafana/grafana#6841 is not marked with any milestone yet, I assume it will take a lot of time?

**Comment by bergquist** [comment]
atleast 6months. Backend plugins is much complex then frontend plugins

**Comment by Mariushrek** [comment]
Hello, any news connected to JSON Datasource and allerts? :-)

**Comment by nitin-tm** [comment]
Any update on Alerts for JSON data source ?

**Comment by daniellee** [comment]
Won't happen this year. We have delayed backend plugins to focus on other features.

**Comment by carsten-lund** [comment]
Status?

**Comment by andig** [comment]
When it happens we'd be happy to support this from the (enhanced json source)[https://github.com/simPod/grafana-json-datasource]

**Comment by ShilpaSivanesan** [comment]
Does backend-updated branch supports alerting? #119

**Comment by tomisaacson** [comment]
I'm running Grafana v6.0.2 with https://github.com/simPod/grafana-json-datasource. I tried adding a simple alert before I realised it wasn't implemented and it sort of worked:
* I received an alert email with my custom text and a picture of my graph but it then said:

> Error message
> tsdb.HandleRequest() error Could not find executor for data source type: simpod-json-datasource

* When I go back into the alert setup I get the message:
> The datasource does not support alerting queries

So it sort of works. I see it's already been implemented for other plugins in https://github.com/grafana/grafana/issues/5858. Can the remaining work be done by adding this function on the plugin side?

**Comment by andig** [comment]
@daniellee I understand alterting is only for backend data sources? If there is anyything that a frontend datasource could do to support alerting I‘d appreciate a pointer so we could start adding support for the enhanced json source.

**Comment by shakefu** [comment]
Just got bit by this not realizing SimpleJSON is a frontend source even when proxied via Grafana. :(

**Comment by andig** [comment]
Right. Grafana just does the actual http call to circumvent any CORS etc, but not the actual processing.

**Comment by tuckson** [comment]
August 2019 now. Still " The datasource does not support alerting queries"
Really would love to hve that one fixed because it would be exactly what I need.

**Comment by viboga** [comment]
Trying to alert based on Azure Data Explorer, Is there any timeline where this would be implemented..

**Comment by txjmb** [comment]
Add my vote.  2022 now.

**Comment by cosmincrihan** [comment]
Any updates on this?
I, too, am in need of alerts for the JSON data source.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
