### ISSUE TITLE
Tag releases in Git

### ISSUE THREAD

**Issue by kfdm** [grafana/simple-json-datasource#51]
Could you tag the releases in git ? I think that would make it easier for those who want to deploy a tag from git instead of installing from the grafana cli. Thank you :)

**Comment by bergquist** [comment]
Good idea. But closing this since its not an issue :)

**Comment by kfdm** [comment]
I could try re-wording it as more of an issue if you would prefer :)

I hope future updates will be tagged to make it easier to connect the release on grafana.net with the code here :)
