### ISSUE TITLE
When will this plugin support Grafana 4.X.X

### ISSUE THREAD

**Issue by edward4721** [grafana/simple-json-datasource#52]
As title
Cuz I saw this plugin in my plugin list, but I cannot see it when I am creating data source

**Comment by csueiras** [comment]
I'm successfully using this plugin in Grafana 4.1.2

**Comment by edward4721** [comment]
I am using 4.2.0-beta1

**Comment by daniellee** [comment]
It does work in 4.2.0. Have you created your own custom backend?  Here is an [example](https://github.com/bergquist/fake-simple-json-datasource).
