### ISSUE TITLE
/search arguments are not updated during typing

### ISSUE THREAD

**Issue by AriSuutariST** [grafana/simple-json-datasource#55]
When I add a new query using simple-json-datasource, the metric field reads "select metric".
When I start typing something there, the /search is called on my server, but the request
is always "{ target: 'select metric'}". 

I was hoping that it would be updated when I type, ie. if the metric name would be "temp" 

after typing "t" request would be { target: 't' }
after typing "e" request would be { target: 'te' }
after typing "m" request would be { target: 'tem'}
etc etc

This would allow me to return matching metric names for user to choose from.

**Comment by momania** [comment]
This is quite a big issue for me too, as I have a big set of metrics to query. Just returning all available targets without any filtering makes the input panel very slow or even unresponsive.

**Comment by daniellee** [comment]
Fixed by 910a364ff028887c61ce72264cb55db6426ab8bc
