### ISSUE TITLE
Using django database as datasource

### ISSUE THREAD

**Issue by luvpreetsingh** [grafana/simple-json-datasource#56]
I am not clear about the working of this plugin. 
I will have to give grafana a URL of the api, and it will send the request data to which it will get some response.  

I want to see my django database in which models are stored in grafana, How can I see that in grafana ?

**Comment by simPod** [comment]
Can you provide more details what are you asking about please?

You can find 4 required REST endpoints with examples in [README.md](https://github.com/grafana/simple-json-datasource#simple-json-datasource---a-generic-backend-datasource) that your source API must implement. How you connect your django database to the REST API is up to you.
