### ISSUE TITLE
Python backend example

### ISSUE THREAD

**Issue by linar-jether** [grafana/simple-json-datasource#60]
I've uploaded a snippet that provides a python backend for this plugin using flask and pandas for timeseries/table queries

https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850

Maybe useful to list it as an example?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
