### ISSUE TITLE
Templating with simple-jason sending nested variables twice

### ISSUE THREAD

**Issue by moeiniz** [grafana/simple-json-datasource#61]
Hi,

I've got three template variables A,B and C. The result from A feeds the query in B and also the result from B feeds the query in C.
Changing the value in A to a2 will give us b2. The issue is when a value is selected for B (ex. b1) and i change the value for A (ex. from a1 to a2) there are two outgoing requests instead of one.  The outgoing request for B are both the old value(b1) and the new one(b2) while only b2 should've been sent. 
The data source returns both of the request correctly but the results for the one that got computed faster gets displayed. In our case b1 feeds C and results c1 because b1 gets computed faster than b2 which gives us c2.  
Hope I've explained the issue well enough.

<ul>
<li>
<p>What Grafana version are you using?<br>
v4.2.0 (commit: 349f3eb)</p>
</li>
<li>
<p>What datasource are you using?<br>
simplejson</p>
</li>
<li>
<p>What OS are you running grafana on?<br>
ubuntu 4.4.0-75-generic x86_64</p>
</li>
<li>
<p>What did you do?<br>
Changed the selected item for variable A to a2</p>
</li>
<li>
<p>What was the expected result?<br>
c2 should have been displayed in C</p>
</li>
<li>
<p>What happened instead?<br>
c1 is show in C because b1 was previously selected in B</p>
</li>
</ul>

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
