### ISSUE TITLE
Leaf metrics possible?

### ISSUE THREAD

**Issue by matthenning** [grafana/simple-json-datasource#62]
Is it possible to mark targets in a /search response to allow child/leaf nodes?

Meaning if the first target returned by /search is "Living room" can I mark it as having no metrics but child nodes like "Temperature Sensor" which either have more child nodes or a metric like "23.5 °C"?
Grafana would add another drop down menu to select child nodes until a node with an actual metric is returned by /search, like this:

![image](https://cloud.githubusercontent.com/assets/5699183/25898335/054a14e2-358c-11e7-94a6-5a0fb6ac807a.png)

**Comment by kosta** [comment]
From looking at the simple-json-datasource source code, I do not think this is possible at the moment.

**Comment by efficks** [comment]
@kosta What would it take to make it possible.
I want to do a hyerarchy of metric. like host1/process/process1/cpu etc...
Il was hoping something to do recursive stuff. Like the plugin could do an other request to /search with a "host1" and I will return something like ["process","memory"] and a call to the target "host1.process" would return ["process1", "process2", etc]

Thank you

**Comment by kosta** [comment]
Well, one would need to implement such functionality. I'm not an expert on grafana so I don't know how to do this exactly. But looking around the graphite plugin code, it should certainly be possible. 

I'm not sure though if this is in scope for the simple-json-datasource plugin or if this would need to go into a slightly-more-comples-json-datasource plugin ;)

(Note: I'm not a grafana dev, I was just wondering the same thing a few weeks ago and found this issue with an unanswered question. After looking through the code, was able to answer that it's currently not possible)

**Comment by andig** [comment]
cc @alexanderzobnin I'd love to support hierarchical metrics with the json datasource. Looking at the [graphite plugin](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/graphite/graphite_query.ts) it's quite complex. Are you aware of any bare-bones example for a more advanced query editor?

**Comment by andig** [comment]
> I'm not sure though if this is in scope for the simple-json-datasource plugin or if this would need to go into a slightly-more-complex-json-datasource plugin ;)

I think it is. It's already supporting `metricFindQuery`- that might as well handle `children` ;)

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
