### ISSUE TITLE
Send custom token to server

### ISSUE THREAD

**Issue by enexusde** [grafana/simple-json-datasource#64]
While adding a datasource to grafana there is a test (200 OK) for the root datasource.

This is a problem because we use the URL for other services too who needs a 204. 

So I need to send 204 or 200, depending on if it is simple-json-datasource-check or not.

**Workaround:** To identify the service as "simple-json-datasource"-check I need a extra request header (Please respect rfc6648) or an attribute in the URL. Currently I check the "Referer" and scan "datasources/edit", it works but it is a bad idea.

**Comment by daniellee** [comment]
There is some support for this at the plugin metadata level. If you fork the project, you can add your headers like this:

https://github.com/grafana/azure-monitor-datasource/blob/master/src/plugin.json#L40-L47

In the example, above if the url starts with "appinsights" then it will add the X-API-Key reqyest header. Not sure if that helps?
