### ISSUE TITLE
Error when choose simplejson on datasource

### ISSUE THREAD

**Issue by oyi77** [grafana/simple-json-datasource#67]
there is an error when i try to choose the simplejson datasource 
the error is : Plugin Error
(SystemJS) XHR error (404 Not Found) loading /public/app/plugins/datasource/grafana-simple-json-datasource/module.js?bust=1496890891487 Error loading /public/app/plugins/datasource/grafana-simple-json-datasource/module.js

Can someone tell me how to fix this?

**Comment by EtiAggarwal** [comment]
I am getting the same error!.

**Comment by torkelo** [comment]
use grafana-cli and or install it into your external plugins dir (specified in grafana.ini)
