### ISSUE TITLE
Bad String Error

### ISSUE THREAD

**Issue by p2ya** [grafana/simple-json-datasource#68]
When I pass Example request through Postman, it throughs an error as bad string at line 18:
{ "target": "upper_50", refId: "A" },
by adding "" to refId it is fixed.
How can this be fixed ? am I missing something ?

**Comment by p2ya** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Failed to decode JSON object: Expecting property name enclosed in double quotes: line 18 column 30 (char 322)</p>

**Comment by torkelo** [comment]
JSON needs property keys enclosed in quotes, your server seems to be returning non valid JSON

**Comment by p2ya** [comment]
Please check:
https://community.grafana.com/t/simple-json-datasource-bad-string-error/1343/6
