### ISSUE TITLE
When you do a GET request to '/', and  response has some data, even if server sends '200', grafana throws an error 

### ISSUE THREAD

**Issue by chenchix** [grafana/simple-json-datasource#75]
When run the plugin against a backend that connect correctly (it returns 200 OK), but some text in the response, it throws an error.

Below is an example of the server response captured from wireshark

> HTTP/1.1 200 OK
> Server: Apache-Coyote/1.1
> Content-Type: application/json;charset=UTF-8
> Content-Length: 4
> Date: Thu, 31 Aug 2017 12:20:39 GMT
> 
> pong

And grafana says that when you press the "Save and test" button.

> 
> Unknown error
> Unexpected token p in JSON at position 0
>

**Comment by daniellee** [comment]
Why are you returning plain text instead of JSON? If it was `{ "pong": ""}` then it would be fine.

**Comment by chenchix** [comment]
I cannot change the server response. 

In the other hand, the API says that only a 200 is needed to validate the petition, but a json is mandatory too.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
