### ISSUE TITLE
Support $__timeFilter and other global variables for templating

### ISSUE THREAD

**Issue by omarmarquez** [grafana/simple-json-datasource#78]
This is a really useful datasource but the global and or scope  variables available to other datasources, $timeFilter or $__timeFilter, are not instantiated(replaced with actual values)  by grafana when querying the source.

Please add global variables support to the templating logic.

**Comment by simPod** [comment]
filter is passed in those fields

```json
  "range": {
    "from": "2016-10-31T06:33:44.866Z",
    "to": "2016-10-31T12:33:44.866Z",
    "raw": {
      "from": "now-6h",
      "to": "now"
    }
  },
  "rangeRaw": {
    "from": "now-6h",
    "to": "now"
  },
```

**Comment by conet** [comment]
Please merge this, I'm using this datasource as a proxy to do queries that grafana does not support, having the variables in the request would be huge benefit.

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
