### ISSUE TITLE
[Question] Using template variables with SimpleJson

### ISSUE THREAD

**Issue by dannaril** [grafana/simple-json-datasource#8]
Hi All,
I'm trying to use this plugin: https://grafana.net/plugins/grafana-simple-json-datasource and build my own data series. I've follow all the instructions of User Guide and I can plot the example series (Upper_25, Upper_50, etc) in the chart. However, when I try to use metrics or create a template variables, grafana is not recognizing it. 
Is it possible to grafana provide the same resources as we have using InfluxDB, or any other data source, using a SimpleJson source?
Thank you very much!
BR,
Danilo

**Comment by bergquist** [comment]
This have been added to 1.1.0 and will soon be available on grafana.net

**Comment by RashmiSaravanan16** [comment]
Is this feature added to grafana ???

**Comment by RainyAngel** [comment]
Is there any documentation on this feature? I cannot figure out how to create a variable in grafana yet the documentation talks about this feature with no explanation on how to use it.
