### ISSUE TITLE
Plugin does not work after fresh install

### ISSUE THREAD

**Issue by Silvester23** [grafana/simple-json-datasource#80]
I just did a fresh install of Grafana (v 4.6.1) and installed the simple-json-datasource plugin via `sudo grafana-cli plugins install grafana-simple-json-datasource`

However, if I try to add a new datasource and choose SimpleJson as the type, I get the error

> Error: Unable to dynamically transpile ES moduleA loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.Instantiating http://localhost:3000/public/plugins/grafana-simple-json-datasource/module.jsLoading plugins/grafana-simple-json-datasource/moduleStack trace:re@http://localhost:3000/public/build/0.7d03bf00820ec00459ae.js:1:485621Zt/<@http://localhost:3000/public/build/0.7d03bf00820ec00459ae.js:1:482739S/</<@http://localhost:3000/public/build/vendor.2305a8e1d478628b1297.js:15:579179S/<@http://localhost:3000/public/build/vendor.2305a8e1d478628b1297.js:15:579049l@http://localhost:3000/public/build/vendor.2305a8e1d478628b1297.js:2:35691

**Comment by simPod** [comment]
Try it now, I had no issues
