### ISSUE TITLE
Alert is not working

### ISSUE THREAD

**Issue by addysunn** [grafana/simple-json-datasource#82]
Hello, 
I am using simple-json-datasource  to connect with my SAP HANA database. When I am creating graph after fetching data from HANA DB I am not able to set up an alerts feature with the graph. Please let me know if there is a way I can fix it or if someone faced the same issue.

Error message: 
`tsdb.HandleRequest() could not find executor for datasource type: garafana-simple-json-datasource`

**Comment by bfiaut** [comment]
I think this issue is related to #46

**Comment by simPod** [comment]
I think the same, IMO this can be closed.

**Comment by daniellee** [comment]
This plugin does not have alerting support.

**Comment by chuangyeshuo** [comment]
why we don`t make it have alerting support ?
