### ISSUE TITLE
Live reload of plugins in dev mode

### ISSUE THREAD

**Issue by gianluca-sabena** [grafana/simple-json-datasource#9]
I'm developing a plugin datasource for grafana 3. I have a running grafana server with app_mode = developmente. I modified this repo grunt file to publish to ```grafana_server/public_gen/app/plugins/datasource/grafana-simple-json-datasource``` but I have to restart grafana server every time I want to test my updates

Is it possible to have grafana server to automatically reload files in public_gen/folder?

**Comment by bergquist** [comment]
@gianluca-sabena I suggest you place the plugin your developing in the plugin folder instead. /var/lib/grafana if installed as a server or <grafana-dir>/data/plugins in developement mode.

You can then have a grunt watch task in the plugin dir for just that plugin.
