### ISSUE TITLE
Metrics not displaying with proper date time

### ISSUE THREAD

**Issue by TryTryAgain** [grafana/simple-json-datasource#90]
I have added my own json datasource using unix epoch time in milliseconds for the datapoints but instead of showing the metrics in the graph for the correct date time it only displays them in one minute intervals. This is true for the fake-simple-json-datasource as well. Is there something simple I need to change in the grafana dashboard to get the correct time?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
