### ISSUE TITLE
unable to authenticate to an api which issues tokens

### ISSUE THREAD

**Issue by danish09** [grafana/simple-json-datasource#92]
Hi, 

I am using simpleJson 1.3.5. 

I am trying to query a REST API endpoint which spits out JSON. This endpoint issues api tokens and am trying to configure the simpleJson tool to authenticate with it but I just cannot get my head around it. Not sure if its possible in the tool itself. Therefore raising the issue.

Thanks

**Comment by damovsky** [comment]
same here. Could not use REST API from CloudCheckr (https://support.cloudcheckr.com/cloudcheckr-api-userguide/)

anyone able to use simple json with API where URL format is
`https://URL?access_key=[access_key]`
?

**Comment by sanjajee** [comment]
I too have similar use case where i need to read data from rest api which will issue the token.on next request i need to send the token as request parameter to achieve the successful authentication.

Could you please help to solve this issue in using simple json datasource plugin

**Comment by sachinteotia30** [comment]
Can someone please provide pointers to fix this issue?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
