### ISSUE TITLE
Iframe with username and password in reverseproxy

### ISSUE THREAD

**Issue by mohanraj1939** [grafana/simple-json-datasource#93]
Hi all,

I’m trying to pass username & Password in URL with apache2 as reverse proxy, we can say it even using the same URL in IFRAME. But i can’t to access the plugins. it throws error like instantiating, screenshot is enclosed for reference.

I’m using simplejson as datasource, due to which i’m unable to obtain a dashboard.

I’m using grafana version 5.0.4, Simple JSON version 1.3.5.

![grafana error](https://user-images.githubusercontent.com/33648564/41018901-d41d924a-6979-11e8-8285-5f7abf381ed0.png)

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
