### ISSUE TITLE
How Can I Send Query Parameters ?

### ISSUE THREAD

**Issue by ishallbethat** [grafana/simple-json-datasource#94]
The query example from README is sending by method "POST" and what i want is send the request with parameters, like 
I want to get cpu of certain nodes and i will request with a list of node ips.
How can i achieve this with this simple json datasource ? 

> 

`{
 "panelId": 1,
 "range": {
 "from": "2016-10-31T06:33:44.866Z",
 "to": "2016-10-31T12:33:44.866Z",
 "raw": {
 "from": "now-6h",
 "to": "now"
 }
 },
 "rangeRaw": {
 "from": "now-6h",
 "to": "now"
 },
 "interval": "30s",
 "intervalMs": 30000,
 "targets": [
 { "target": "upper_50", "refId": "A", "type": "timeserie" },
 { "target": "upper_75", "refId": "B", "type": "timeserie" }
 ],
 "format": "json",
 "maxDataPoints": 550
}`

**Comment by andig** [comment]
#100 and #104 could work for you

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
