### ISSUE TITLE
Parameter Interpolation Format Changed

### ISSUE THREAD

**Issue by rfarnham** [grafana/simple-json-datasource#98]
In the old `SimpleJSONDatasource`, parameter interpolation used `glob` syntax, now it seems to use `regex` syntax. We have custom backend data sources which expect the old glob syntax.
It seems that the relevant line change is here: https://github.com/grafana/simple-json-datasource/blob/2228bcf0fbe7cafd90fe7966cd66754a2f30c670/src/datasource.js#L112

Is it possible to make the parameter interpolation strategy configurable?

**Comment by itsgareth** [comment]
The Simple JSON Datasource is now deprecated, and as a result, we are closing all open issues in this repository.
Our development focus has shifted, and we are no longer actively maintaining this plugin.

This deprecation means that this plugin won’t receive any feature updates or bug fixes except critical security fixes.
After 6 months of the deprecation date (End of June 2024), no updates will be provided at all.

We recommend migrating to the Infinity datasource. Here are the [migration steps](https://github.com/grafana/grafana-infinity-datasource/discussions/740) you can follow.
Thank you for your understanding.
